---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs
  namespace: monitoring
  labels:
    bucket: shared
spec:
  capacity:
    storage: 4T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: monitoring
    name: grafana-storage
  nfs:
    server: 192.168.1.192
    path: "/home/pi/nas/grafana"
