---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-nfs
  namespace: monitoring
  labels:
    bucket: shared
spec:
  capacity:
    storage: 4T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: monitoring
    name: prometheus-k8s-db-prometheus-k8s-0
  nfs:
    server: 192.168.1.192
    path: "/home/pi/nas/prometheus"
